# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20171003_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(help_text='上传的文件', upload_to='user_operation/files/', verbose_name='上传的文件'),
        ),
    ]
