# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-14 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_time',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f\uff08\u5206\u949f\u6570\uff09'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_time',
            field=models.IntegerField(default=0, verbose_name='\u89c6\u9891\u65f6\u957f\uff08\u5206\u949f\u6570\uff09'),
        ),
    ]
